" Configuration file for vim
"set runtimepath=~/.vim,/usr/share/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vimcurrent,/usr/share/vim/vimfiles/after,/usr/share/vim/addons/after,~/.vim/after,/usr/share/vim/vim73

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
" Source a global configuration file if available
if filereadable("/etc/vimrc")
  source /etc/vimrc
endif

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	"    Use Vim defaults instead of 100% vi compatibility
set backspace=indent,eol,start	" more powerful backspacing
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" original repos on GitHub
Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/syntastic'
Bundle 'mileszs/ack.vim'
Bundle 'majutsushi/tagbar'
Bundle 'ervandew/supertab'
Bundle 'bling/vim-airline'

Bundle 'altercation/vim-colors-solarized'
Bundle 'chriskempson/tomorrow-theme'

Bundle 'pangloss/vim-javascript'
" python
Bundle 'hdima/python-syntax'
Bundle 'hynek/vim-python-pep8-indent'
"Bundle 'davidhalter/jedi-vim'

Bundle 'kien/ctrlp.vim'
Bundle 'jlanzarotta/bufexplorer'

if has("autocmd")
 " Enabled file type detection
 " Use the default filetype settings. If you also want to load indent files
 " to automatically do language-dependent indenting add 'indent' as well.
 filetype plugin indent on
 filetype plugin on
endif " has ("autocmd")

" Theme settings
" set background=dark
set rtp+=~/.vim/bundle/tomorrow-theme/vim
colorscheme Tomorrow-Night

" Now we set some defaults for the editor
set autoindent		    " always set autoindenting on
" set linebreak		    " Don't wrap words by default
set textwidth=0		    " Don't wrap lines by default
set viminfo='20,\"50    " Read/write a .viminfo file, don't store more than
                        " 50 lines of registers.
set history=50		    " keep 50 lines of command line history
set ruler		        " show the cursor position all the time

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
set showcmd		        " Show (partial) command in status line.
set showmatch		    " Show matching brackets.
set ignorecase		    " Do case insensitive matching
set smartcase
set nosmartindent
set hlsearch            " highlight search
nnoremap <leader><space> :noh<cr>
set incsearch		    " Incremental search
"set autowrite		    " Automatically save before commands like :next and :make
if has('mouse')
  set mouse=a             " add mouse interaction
endif

" Highlight column/line
set cursorline
"set cursorcolumn

" Autocomplete in explore
set wildmenu
set wildmode=longest,list
set wildignore=*.o,*.obj,*.bak,*.exe,*.py[co],*.swp,*~,*.class
let mapleader = ","

" Enable syntax-highlighting.
if has("syntax")
  syntax on
endif

" Tell vim which characters to show for expanded TABs,
" trailing whitespace, and end-of-lines. VERY useful!
set listchars=tab:▸\ ,trail:█

" Map .less to .css , lessc is required.
nnoremap ,m :w <BAR> !lessc % > %:t:r.css<CR><space>

" au BufRead,BufNewFile *.py  set ai sw=4 sts=4 et tw=72 " Doc strs
au BufRead,BufNewFile *.js  set ai sw=4 sts=4 et tw=72 " Doc strs
au BufRead,BufNewFile *.html set ai sw=4 sts=4 et tw=72 " Doc strs
au BufRead,BufNewFile *.json set ai sw=4 sts=4 et tw=72 " Doc strs
au BufRead,BufNewFile *.less set ai sw=4 sts=4 et tw=72 " Doc strs
au BufRead,BufNewFile *.sql set ai sw=4 sts=4 et
au! BufRead,BufNewFile *.json setfiletype json
au BufNewFile,BufRead *.less set filetype=less
au BufNewFile,BufRead *.styl set filetype=styl

" This makes Vim show a status line even when only one window is shown. Who
" said a status line is only useful to separate multiple windows?
set ls=2

" We know xterm-debian is a color terminal
if &term =~ "xterm-debian" || &term =~ "xterm-xfree86"
  set t_Co=16
  set t_Sf=[3%dm
  set t_Sb=[4%dm
else
  set t_Co=256
endif

" When editing a file, always jump to the last known cursor position.
 " Don't do it when the position is invalid or when inside an event handler
 " (happens when dropping a file on gvim).
autocmd BufReadPost *
   \ if line("'\"") > 0 && line("'\"") <= line("$") |
   \   exe "normal! g`\"" |
   \ endif

"------------------------------------------------------------------------------
" Function keys.
"------------------------------------------------------------------------------
" nnoremap <up> <nop>
" nnoremap <down> <nop>
" nnoremap <left> <nop>
" nnoremap <right> <nop>
" inoremap <up> <nop>
" inoremap <down> <nop>
" inoremap <left> <nop>
" inoremap <right> <nop>
" nnoremap j gj
" nnoremap k gk

nnoremap <leader>a :Ack

nnoremap <leader>b :CtrlPBuffer<cr>
nnoremap <leader>t :CtrlP<cr>
let g:bufExplorerFindActive=0

map <F1> :NERDTreeToggle<cr>
let NERDTreeShowBookmarks=1

set nonumber
nnoremap <F2> :set number!<CR>:set foldcolumn=0<CR>

" <F3>: Toggle hlsearch (highlight search matches).
nmap <F3> :set hls!<CR>

set pastetoggle=<F4>          " activa o desactiva el mode paste

" Toggle list (display unprintable characters).
set list
nmap <F6> :set list!<CR>
nmap <F8> :TagbarToggle<CR>

nnoremap <C-c> :bdelete<CR>
nmap <C-t> :tabnew<cr>
map <C-t> :tabnew<cr>
noremap <D-A-Left> :tabprevious<cr>
noremap <D-A-Right> :tabnext<cr>
map ty :tabclose<cr>
imap <C-t> <ESC>:tabnew<cr>

nmap <C-k> :bp<CR>
nmap <C-j> :bn<CR>

" toggle comments with NERDCommenter
vmap <C-c> <Leader>c<space>gv
map <C-c> <Leader>c<space>

map <leader>cs :mksession! ~/.vim/session<CR>
map <leader>ls :source ~/.vim/session<CR>
