#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

path=(
  $HOME/bin
  $path
)

# Aliases
alias hgrep='history | grep'
alias sctl='supervisorctl'

setopt interactivecomments

# setup base16 sheel
BASE16_SHELL="$HOME/.dotfiles/base16-shell/base16-monokai.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# localrc (machine specific shell config)
[ -e $HOME/.localrc ] && source $HOME/.localrc
